# Generated by Django 5.2.1 on 2025-05-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0004_post_curtidas_alter_comment_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='rede.userprofile'),
        ),
    ]
