# Generated by Django 5.2.1 on 2025-05-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0005_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
