# Generated by Django 5.2.1 on 2025-05-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0006_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='covers/default_cover.png', null=True, upload_to='covers/'),
        ),
    ]
